name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest,macos-14,windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.version}}
        
